/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatInput: typeof import('./src/components/danmaku/ChatInput.vue')['default']
    ChatMessageList: typeof import('./src/components/danmaku/ChatMessageList.vue')['default']
    DanmakuOverlay: typeof import('./src/components/danmaku/DanmakuOverlay.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemNotice: typeof import('./src/components/danmaku/SystemNotice.vue')['default']
  }
}
